name: Trigger test in another Repo
on:
  workflow_dispatch:

jobs: 
  trigger-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Trigger automated test in another repo
        uses: actions/checkout@v2

      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Ps3291/Hello-World-Python
          event-type: my-event
          #client-payload: '{"key": "value"}'
