name: Create CSV File

on:
  workflow_dispatch:
    inputs:
      value_1:
        description: 'Value 1'
        required: true
      value_2:
        description: 'Value 2 (multiple values separated by pipe)'
        required: true
      value_3:
        description: 'Value 3 (numbers only)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
          value1=$(echo "${{ github.event.inputs.value_1 }}" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
          echo "VALUE_1=$value1" >> $GITHUB_ENV
          
          echo "value_11=${{ github.event.inputs.value_1 }}" >> $GITHUB_ENV

          value2="${{ github.event.inputs.value_2 }}"
          if [[ ! $value2 =~ ^[^|]+(\|[^|]+)*$ ]]; then
            echo "Invalid input. Value 2 must be in pipe-delimited format."
            exit 1
          fi
          echo "VALUE_2=$value2" >> $GITHUB_ENV

          value3=${{ github.event.inputs.value_3 }}
          if ! [[ $value3 =~ ^[0-9]+$ ]]; then
            echo "Invalid input. Value 3 must be numeric."
            exit 1
          fi
          echo "VALUE_3=$value3" >> $GITHUB_ENV

      - name: Create CSV file
        run: |
          # Bash script to generate the CSV file
          echo "Column1,Column2,Column3,Column4" > data.csv
          echo "$VALUE_1,$VALUE_2,$VALUE_3,$value_11" >> data.csv
          echo "$VALUE_1,$VALUE_2,$VALUE_3,$value_11" >> data.csv
          echo "$VALUE_1,$VALUE_2,$VALUE_3,$value_11" >> data.csv

      - name: Display CSV content
        run: cat data.csv
        
      - name: Adding Markdown
        run: |
         # input_value_2=$(echo "${{ github.event.inputs.value_2 }}" | sed 's/|/\\|/g')
         echo "|Name|Input|" >> $GITHUB_STEP_SUMMARY
         echo "|-|-|" >> $GITHUB_STEP_SUMMARY
         echo "|**Value**|\`$(${{ github.event.inputs.value_2 }} | sed 's/|/\\|/g')\`|" >> $GITHUB_STEP_SUMMARY




      - name: Archive CSV file
        uses: actions/upload-artifact@v2
        with:
          name: csv-artifact
          path: data.csv
